### ISSUE TITLE
BUG: #include & #includedir not honored

### ISSUE THREAD

**Issue by necrux** [yast/yast-sudo#5]
## Overview
Yast removes all comments from `/etc/sudoers` after the final configuration line, including the `#include` and `#includedir` entries. These are not comments and the proceeding `#` is a [requirement](https://www.sudo.ws/repos/sudo/rev/fbb92a25a726). These entries must also be at the end of the file.

## Expected Behavior
At minimum, yast should not overwrite/remove any existing configuration settings without explicit instruction to do so. The interface *should* also read configuration settings included from `/etc/sudoers` (files and directories).

## Possible Solution
When parsing `$line` match `^#include` as well.

## Steps to Reproduce
1. Append the following to `/etc/sudoers`:
```
## Read drop-in files from /etc/sudoers.d
## (the '#' here does not indicate a comment)
#includedir /etc/sudoers.d
```
2. Open up `yast` -> `Security and Users` -> `Sudo`
3. Hit `Ok` to save the file.
4. Open up `/etc/sudoers` to verify that the newly added lines have been removed.

**Comment by dgdavid** [comment]
Hi @necrux 

First of all, thank you so much for a quite detailed issue report.

It's a little bit shameful to admit it but unfortunately, we overlooked it since we mostly use Bugzilla to track the issues.

The good news: the problem described above was already _fixed_ one month ago. Have a look at https://github.com/yast/yast-sudo/pull/13 is you are interested enough in the details.

Again, thanks for your collaboration. Much appreciated.
